---
title: "Meta HRSL for between-cluster geographical spillover of AMR in MORDOR at 24 months"
# author: "Ariktha Srivathsan"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    code_folding: hide
---

```{=html}
<style type="text/css">

body{ /* Normal  */
      font-size: 12px;
  }
td {  /* Table  */
  font-size: 15px;
}
h1.title {
  font-size: 26px;
  color: Black;
}
h1 { /* Header 1 */
  font-size: 24px;
  color: Black;
}
h2 { /* Header 2 */
    font-size: 20px;
  color: Black;
}
h3 { /* Header 3 */
  color: Black;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>
```

```{r setup}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE) 

rm(list = ls())       

library(here)
library(tictoc)
library(units)
```

```{r Load data and functions}

source(here("R", "00-config.R"))
source(here("R", "00-functions.R"))

# Load HRSL data

pop_raw <- readRDS(here("data", "final", "hrsl_rings.RDS"))

```

```{r Prep data}

# ggplot(data = subset(morb_buff, inner_radius == set_units(10, "km"))) +
#   geom_sf(aes(geometry = ring_geom), fill = "blue", color = "black", alpha = 0.5) +
#   theme_minimal() + geom_sf(data = niger_union, fill = NA, color = "black") +
#   labs(title = "Ring Geometry for 10-20 km rings")

ring_plot_full <- ggplot() +
  geom_sf(data = morb_buff, aes(geometry = ring_geom, fill = as.numeric(outer_radius)), color = "black", alpha = 0.5) +
  theme_minimal() + scale_fill_viridis_c() + geom_sf(data = niger_union, fill = NA, color = "black") +
  labs(title = "Ring Geometry check") + theme(legend.position = "bottom")

ring_plot_clip <- ggplot() +
  geom_sf(data = morb_buff_study, aes(geometry = ring_geom, fill = as.numeric(outer_radius)), color = "black", alpha = 0.5) +
  theme_minimal() + scale_fill_viridis_c() + geom_sf(data = niger_union, fill = NA, color = "black") +
  labs(title = "Ring Geometry check") + theme(legend.position = "bottom")

ring_plot_full | ring_plot_clip

```

```{r}

ggplot(data = aggregated2) +
  geom_point(aes(x = outer_radius, y = study_area_total_gen_pop, group = grappe)) +
  geom_line(aes(x = outer_radius, y = study_area_total_gen_pop, group = grappe), color = "lightgrey", alpha = 0.6) +
  theme_minimal() + labs(title = "Population in ring in the study area", x = "Outer radius (km)", y = "HRSL Population in the study area")

pop_plot <- ggplot(data = aggregated) +
  geom_point(aes(x = outer_radius, y = total_gen_pop, group = grappe)) +
  geom_line(aes(x = outer_radius, y = total_gen_pop, group = grappe), color = "lightgrey", alpha = 0.6) +
  theme_minimal() + labs(title = "Population in ring", x = "Outer radius (km)", y = "HRSL Population in the ring")

plotly::ggplotly(pop_plot)

```

# Population density

```{r}

morb_ring <- morb_tx %>% st_drop_geometry() %>%
  left_join(aggregated, by = c("grappe", "outer_radius")) %>%
  dplyr::filter(outer_radius <= 30) %>%
  mutate(u5_pop_dens = total_u5_pop/area)

# gen pop vs u5 pop
ggplot(morb_ring, aes(x = total_gen_pop, y = total_u5_pop)) + geom_point() + geom_smooth(method = "lm") +
  theme_minimal() + 
  labs(title = "General population vs under-5 population", x = "HRSL general population", y = "HRSL under 5 population") + 
  stat_cor() + facet_wrap(~outer_radius)

hrsl_map_dat <- morb_grappe %>% dplyr::select(grappe) %>% distinct() %>%
  right_join(aggregated, by = "grappe") %>%
  mutate(u5_pop_dens = total_u5_pop/area)

# HRSL maps
ggplot() + geom_sf(data = niger_union, fill = "white", color = "black") +
  geom_sf(data = hrsl_map_dat, aes(color = total_u5_pop, size = total_u5_pop), alpha = 0.4) +
  labs(title = "u5 population in MORDOR rings") + facet_wrap(~outer_radius) + 
  scale_color_viridis_c(name = "u5 population") + scale_size_continuous(name = "u5 population") +
  scale_x_continuous(breaks = c(2.4, 2.8, 3.2, 3.6), limits = c(2.45, 3.78), name = "Longitude") + 
  scale_y_continuous(limits = c(12.28, 13.95), name = "Latitude") + annotation_scale() +
  theme_minimal() + theme(legend.position = "bottom") +
  guides(color = guide_legend(override.aes = list(alpha = 0.7), reverse = TRUE), 
         size = guide_legend(reverse = TRUE))

ggplot() + geom_sf(data = niger_union, fill = "white", color = "black") +
  geom_sf(data = subset(hrsl_map_dat, grappe != "SETTI I"), aes(color = total_u5_pop, size = total_u5_pop), alpha = 0.4) +
  labs(title = "u5 population in MORDOR rings: Excluding SETTI I") + facet_wrap(~outer_radius) + 
  scale_color_viridis_c(name = "u5 population") + scale_size_continuous(name = "u5 population") +
  scale_x_continuous(breaks = c(2.4, 2.8, 3.2, 3.6), limits = c(2.45, 3.78), name = "Longitude") + 
  scale_y_continuous(limits = c(12.28, 13.95), name = "Latitude") + annotation_scale() +
  theme_minimal() + theme(legend.position = "bottom") +
  guides(color = guide_legend(override.aes = list(alpha = 0.7), reverse = TRUE), 
         size = guide_legend(reverse = TRUE))

ggplot() + geom_sf(data = niger_union, fill = "white", color = "black") +
  geom_sf(data = subset(hrsl_map_dat, grappe != "SETTI I"), aes(color = u5_pop_dens, size = u5_pop_dens), alpha = 0.4) +
  labs(title = "u5 population/area in MORDOR rings: Excluding SETTI I") + facet_wrap(~outer_radius) + 
  scale_color_viridis_c(name = "u5 pop density") + scale_size_continuous(name = "u5 pop density") +
  scale_x_continuous(breaks = c(2.4, 2.8, 3.2, 3.6), limits = c(2.45, 3.78), name = "Longitude") + 
  scale_y_continuous(limits = c(12.28, 13.95), name = "Latitude") + annotation_scale() +
  theme_minimal() + theme(legend.position = "bottom") +
  guides(color = guide_legend(override.aes = list(alpha = 0.7), reverse = TRUE), 
         size = guide_legend(reverse = TRUE))

# HRSL meets MORDOR

morb_ring <- morb_ring %>% rename(arm = arm.x)

ggplot(morb_ring, aes(y = total_u5_pop, group = arm, color = arm, x = arm)) + geom_boxplot() + facet_wrap(~outer_radius) +
  theme_minimal() + labs(title = "HRSL under-5 population by ring and arm") + theme(legend.position = "none")

ggplot(subset(morb_ring, grappe != "SETTI I"), aes(y = u5_pop_dens, group = arm, color = arm, x = arm)) + 
  geom_boxplot() + facet_wrap(~outer_radius) +
  theme_minimal() + labs(title = "HRSL under-5 pop density by ring and arm: Excluding SETTI I") + theme(legend.position = "none")

ggplot(morb_ring, aes(x = total_u5_pop, y = total_children)) + geom_point() + facet_wrap(~outer_radius) +
  theme_minimal() + labs(title = "HRSL under-5 population vs MORDOR total children by ring") + stat_cor() +
  geom_abline(intercept = 0, slope = 1, color = "lightgrey")

ggplot(subset(morb_ring, grappe != "SETTI I"), aes(x = total_u5_pop, y = total_children)) + geom_point() + facet_wrap(~outer_radius) +
  theme_minimal() + labs(title = "HRSL under-5 population vs MORDOR total children by ring: SETTI I excluded") + stat_cor() +
  geom_abline(intercept = 0, slope = 1, color = "lightgrey")

ggplot(subset(morb_ring, grappe != "SETTI I"), aes(x = total_u5_pop/area, y = total_children/area)) + 
  geom_point() + facet_wrap(~outer_radius) +
  theme_minimal() + 
  labs(title = "HRSL u5 pop/area vs MORDOR total children/area by ring: SETTI I excluded", 
       x = "HRSL u5 population density", y = "MORDOR number of children/area") + 
  stat_cor() +
  geom_abline(intercept = 0, slope = 1, color = "lightgrey")

```

# Assess confounding by population density

## (c -> e) Association between population density and treatment intensity

```{r}

morb_ring_doses <- morb_ring %>%
  dplyr::select(grappe, outer_radius, total_u5_pop, u5_pop_dens, total_doses, azithro_doses, placebo_doses) %>%
  pivot_longer(cols = c(total_doses, azithro_doses, placebo_doses), names_to = "dose_type", values_to = "doses")

# ggplot(subset(morb_ring_doses, dose_type == "azithro_doses"), aes(x = u5_pop_dens, y = doses)) + geom_point() +
#   theme_minimal() + labs(title = "Under-5 pop density vs azithro doses by ring") + 
#   stat_cor() + facet_wrap(~outer_radius)

# ggplot(subset(morb_ring_doses, dose_type == "azithro_doses" & grappe != "SETTI I"), aes(x = u5_pop_dens, y = doses)) + geom_point() +
#   theme_minimal() + 
#   labs(title = "Under-5 pop density vs azithro doses by ring: SETTI I excluded") + 
#   stat_cor() + facet_wrap(~outer_radius)

morb_ring_doses <- morb_ring_doses %>% left_join(morb_grappe %>% dplyr::select(grappe, arm), by = "grappe")

ggplot(subset(morb_ring_doses, grappe != "SETTI I"), aes(x = u5_pop_dens, y = doses, color = arm, group = arm)) + geom_point() +
  theme_minimal() + stat_cor() + facet_grid(vars(outer_radius), vars(dose_type)) +
  labs(title = "Under-5 pop density vs doses by ring: SETTI I excluded", x = "Under-5 population density", y = "Doses") +
  scale_color_manual(values = arms_colors)

ggplot(subset(morb_ring, grappe != "SETTI I"), aes(x = u5_pop_dens, y = azithro_int, color = arm, group = arm)) + geom_point() +
  theme_minimal() +
  labs(x = "Under-5 population density", y = "Azithromycin treatment intensity") + 
  stat_cor() + facet_wrap(~outer_radius) +
  scale_color_manual(values = arms_colors) + theme(legend.position = "bottom")

```

## (c -> o) Association between population density and AMR

```{r}

amr_dat <- amr_dat_raw %>% dplyr::filter(ab_class == "MLS") %>%
  dplyr::select(phase, grappe, avg_res)

morb_ring_amr <- morb_ring %>% left_join(amr_dat, by = "grappe") %>%
  dplyr::select(grappe, phase, outer_radius, total_u5_pop, u5_pop_dens, avg_res, azithro_doses) %>% 
  left_join(morb_grappe %>% dplyr::select(grappe, arm), by = "grappe") %>%
  mutate(phase_txt = ifelse(phase == 0, "Baseline", "24 months"),
         ring_txt = case_when(outer_radius == 10 ~ "0 - 10 km",
                              outer_radius == 20 ~ "10 - 20 km",
                              outer_radius == 30 ~ "20 - 30 km")) %>%
  mutate(phase_txt = factor(phase_txt, levels = c("Baseline", "24 months"), ordered = TRUE))

ggplot(subset(morb_ring_amr, grappe != "SETTI I"), aes(x = u5_pop_dens, y = avg_res, color = arm, group = arm)) + geom_point() +
  theme_minimal() + labs(x = "Under-5 population density", y = "MLS resistance") + 
  stat_cor() + facet_wrap(~ phase_txt + ring_txt) +
  scale_color_manual(values = arms_colors) + theme(legend.position = "bottom")

```

```{r plot}

p1 <- ggplot(morb_ring_amr, aes(x = u5_pop_dens, y = azithro_doses, color = arm, group = arm)) + 
  geom_point() +
  theme_minimal(base_size = 12) + 
  stat_cor(method = "spearman", cor.coef.name = "rho", show.legend = FALSE, label.x.npc = "right", label.y.npc = "top", hjust = 1) + 
  facet_wrap(~ring_txt) + 
  scale_y_continuous(labels = function(x) x/1000, name = expression(atop("Azithromycin doses", "in the band x"~10^3)), limits = c(0, 30000)) +
  scale_x_continuous(name = "Population density of children under 5 years old", limits = c(0, 40)) +
  theme(legend.position = "bottom", panel.spacing.x = unit(0.6, "cm"), axis.title.y = element_text(hjust = 0.5)) +
  scale_color_manual(name = "Monitoring village treatment", breaks = c("azithro", "placebo"), labels = c("Azithromycin", "Placebo"), values = arms_colors)

p2 <- ggplot(morb_ring_amr, aes(x = u5_pop_dens, y = avg_res, color = arm, group = arm)) + 
  geom_point() +
  theme_minimal(base_size = 12) + 
  labs(y = "MLS resistance gene abundance\n(normalized reads/million)") +
  scale_x_continuous(name = "Population density of children under 5 years old\nData from High Resolution Settlement Layer, Meta data for good", limits = c(0, 40)) + 
  stat_cor(method = "spearman", cor.coef.name = "rho", show.legend = FALSE, label.x.npc = "right", label.y.npc = "top", hjust = 1) + 
  facet_grid(phase_txt ~ ring_txt, switch = "y") +
  # facet_wrap(~ phase_txt + ring_txt) +
  scale_color_manual(name = "Monitoring village treatment", breaks = c("azithro", "placebo"), labels = c("Azithromycin", "Placebo"), values = arms_colors) +
  theme(legend.position = "bottom", panel.spacing.x = unit(0.6, "cm")) + 
  ylim(c(0, 200))

hrsl_plot <- p1 / p2 + 
  plot_annotation(tag_levels = 'A') + plot_layout(heights = c(0.4, 0.6), guides = "collect")  &
  theme(legend.position = 'bottom')

ggsave(here("figs", "24-months", "hrsl_plot.png"), hrsl_plot, width = 8, height = 7, dpi = 600, bg = "white")

```

# Edge effects

```{r}

ggplot(data = aggregated) + geom_point(aes(x = total_gen_pop, y = study_area_total_gen_pop)) +
  facet_wrap(~outer_radius) + geom_abline(intercept = 0, slope = 1, color = "lightgrey") +
  theme_minimal() + labs(title = "Population in ring: Full vs study area", x = "HRSL Population in the ring", y = "HRSL Population in the ring and study area")

ggplot(data = aggregated) + 
  geom_point(aes(x = total_gen_pop, y = study_area_total_gen_pop, size = prop_in_study_area, color = arm), alpha = 0.5) +
  facet_wrap(~outer_radius) + geom_abline(intercept = 0, slope = 1, color = "lightgrey") +
  theme_minimal() + labs(title = "Population in ring: Full vs study area", x = "HRSL Population in the ring", y = "HRSL Population in the ring and study area") +
  scale_size_continuous(name = "Proportion of ring\nin study area") + scale_color_manual(values = arms_colors)

```