---
title: "Distance to closest CSI for between-cluster geographical spillover of AMR in MORDOR at 24 months"
# author: "Ariktha Srivathsan"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    code_folding: hide
---

```{=html}
<style type="text/css">

body{ /* Normal  */
      font-size: 12px;
  }
td {  /* Table  */
  font-size: 15px;
}
h1.title {
  font-size: 26px;
  color: Black;
}
h1 { /* Header 1 */
  font-size: 24px;
  color: Black;
}
h2 { /* Header 2 */
    font-size: 20px;
  color: Black;
}
h3 { /* Header 3 */
  color: Black;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>
```

```{r setup}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE) 

rm(list = ls())       

library(here)
library(units)
library(patchwork)
library(ggpubr)
```

```{r Load data and functions}

source(here("R", "00-config.R"))
source(here("R", "00-functions.R"))

# Load MORDOR morbidity and main trial data

morb_grappe_raw <- readRDS(here("data", "final", "morb_grappe.RDS"))
morb_gps <- readRDS(here("data", "final", "morb_gps.RDS"))
morb_grappe <- morb_grappe_raw %>%
  left_join(morb_gps, by = "grappe") %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = global_crs)

morb_tx <- readRDS(here("data", "final", "morb_tx_int.RDS"))

amr_dat_raw <- readRDS(here("data", "final", "amr_dat.RDS"))

# Load Niger map from Humanitarian Data Exchange 
# Map downloaded from https://data.humdata.org/dataset/cod-ab-ner on 9 April 2024

niger_shp <- st_read(here("data", "untouched", "niger_shapefiles", "NER_admbnda_adm2_IGNN_20230720.shp"))

niger_union <- niger_shp %>% 
  mutate(mordor_states = ifelse(ADM2_FR %in% c("Falmey", "Boboye", "Loga"), TRUE, FALSE)) %>% 
  dplyr::filter(mordor_states == TRUE) %>% st_union()

# Load data on CSI locations

csi_loc_raw <- data.table::fread(here("data", "untouched", "cartesanitaire_niger_entites.csv"))

```

## 1680 CSIs don't have a location!!!

```{r}

csi_loc <- csi_loc_raw %>% 
  mutate(lat_lon = map(Coordinates, ~ {
                         if (!is.na(.x)) {
                           # Remove spaces and extract numbers
                           clean_coords <- gsub("\\s+", "", .x)
                           matches <- regmatches(clean_coords, gregexpr("-?\\d+\\.\\d+", clean_coords))[[1]]
                           if (length(matches) >= 2) {
                             as.numeric(matches)
                           } else {
                             c(NA_real_, NA_real_)
                           }
                         } else {
                           c(NA_real_, NA_real_)
                         }
                       }),
         latitude = map_dbl(lat_lon, 1),
         longitude = map_dbl(lat_lon, 2)) %>%
  dplyr::select(`Dhis2 Id`, latitude, longitude) %>%
  drop_na() %>%
  rename(dhis2_id = `Dhis2 Id`) %>%
  st_as_sf(coords = c("latitude", "longitude"), crs = 4326) %>%
  mutate(latitude = st_coordinates(.)[, 2],
         longitude = st_coordinates(.)[, 1]) %>%
  dplyr::filter(latitude != 0)

csi_proj <- st_transform(csi_loc, crs = proj_crs)
morb_proj <- st_transform(morb_grappe, crs = proj_crs)

morb_csi <- st_distance(morb_proj, csi_proj, by_element = FALSE) %>%
  units::set_units("km") %>%
  as.matrix() %>%
  as.data.frame() %>%
  `colnames<-`(csi_proj[["dhis2_id"]]) %>%
  mutate(grappe = morb_proj[["grappe"]]) %>%
  pivot_longer(-grappe, names_to = "dhis2_id", values_to = "distance") %>%
  mutate(distance = as.numeric(distance))

morb_nearest_csi <- morb_csi %>%
  group_by(grappe) %>%
  slice_min(distance, with_ties = FALSE) %>%
  ungroup()

morb_grappe <- morb_grappe %>% 
  left_join(morb_nearest_csi, by = "grappe")

morb_csi <- morb_grappe %>%
  dplyr::select(grappe, dhis2_id, distance) %>%
  rename(csi_name = dhis2_id, dist_csi = distance)

saveRDS(morb_csi, here("data", "final", "morb_csi.RDS"))

```

```{r}

csi_plot <- st_crop(csi_loc, niger_union) 

map1 <- ggplot() + geom_sf(data = niger_union, fill = NA) +
  geom_sf(data = csi_plot, shape = 21, size = 2, fill = "red", alpha = 0.2) +
  geom_sf(data = morb_grappe) + theme_minimal()

map2 <- ggplot() + geom_sf(data = niger_union)  +
  geom_sf(data = morb_grappe, aes(color = distance, size = distance), alpha = 0.4) +
  scale_color_viridis_c(name = "dist nearest csi (km)") + 
  scale_size_continuous(name = "dist nearest csi (km)") +
  scale_x_continuous(breaks = c(2.4, 2.8, 3.2, 3.6), limits = c(2.45, 3.78), name = "Longitude") + 
  scale_y_continuous(limits = c(12.28, 13.95), name = "Latitude") + 
  ggspatial::annotation_scale() +
  theme_minimal() + theme(legend.position = "bottom") +
  guides(color = guide_legend(override.aes = list(alpha = 0.7)))

map1 + map2

ggplot(morb_grappe, aes(x = arm, group = arm, color = arm, y = distance)) + geom_boxplot() + theme_minimal() +
  theme(legend.position = "none") + labs(x = "Arm", y = "Distance to closest CSI (km)") +
  geom_rug() + 
  scale_color_manual(breaks = c("azithro", "placebo"), values = arms_colors)


```

## (c -> e) Association between distance to nearest CSI and treatment intensity

```{r}

morb_tx_long <- morb_tx %>%
  left_join(morb_nearest_csi, by = "grappe") %>%
  dplyr::filter(idw_power == 1)

ggplot(morb_tx_long, aes(x = tx_int, y = distance, color = arm)) + 
  geom_point() + 
  theme_minimal() + 
  facet_wrap(~ tx_type, nrow = 2) +
  labs(x = "Treatment intensity", y = "Distance to nearest CSI (km)") + 
  ggpubr::stat_cor(label.x.npc = 0.6) +
  scale_color_manual(values = arms_colors)

```

## (c -> o) Association between distance to nearest CSI and AMR

```{r}

amr_dat <- amr_dat_raw %>% dplyr::filter(ab_class == "MLS") %>%
  dplyr::select(phase, grappe, avg_res) %>%
  distinct() %>% 
  left_join(morb_csi %>% st_drop_geometry(), by = "grappe") %>%
  rename(distance = dist_csi) %>%
  left_join(morb_grappe %>% dplyr::select(grappe, arm), by = "grappe")

ggplot(amr_dat, aes(x = distance, y = avg_res, color = arm)) + 
  geom_point() +
  theme_minimal() + 
  xlab("Distance to nearest CSI (km)") + 
  ylab("MLS resistance") +
  stat_cor() + 
  facet_wrap(~ phase, nrow = 2) +
  scale_color_manual(values = arms_colors)

```
