---
title: "Manuscript figure 2 for between-cluster geographical spillover of AMR in MORDOR at 24 months"
# author: "Ariktha Srivathsan"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    code_folding: hide
---

<style type="text/css">

body{ /* Normal  */
      font-size: 12px;
  }
td {  /* Table  */
  font-size: 15px;
}
h1.title {
  font-size: 26px;
  color: Black;
}
h1 { /* Header 1 */
  font-size: 24px;
  color: Black;
}
h2 { /* Header 2 */
    font-size: 20px;
  color: Black;
}
h3 { /* Header 3 */
  color: Black;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>

```{r setup}

knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE,
                      fig.width = 4, fig.height = 6, dpi = 300) 

rm(list = ls())       

library(here)
library(patchwork)
```

```{r load data}
source(here("R", "00-config.R"))

cor_tx_int_raw <- readRDS(here("data", "output", "cor_tx_int.RDS"))
morb_tx_int_raw <- readRDS(here("data", "clean", "morb_tx_int.RDS"))
amr_dat_raw <- readRDS(here("data", "clean", "amr_dat.RDS"))
```

```{r data prep}

cor_tx_int <- cor_tx_int_raw %>%
  dplyr::filter(idw_power == 1) %>%
  dplyr::filter(ab_class == "MLS") %>%
  dplyr::select(- c(ab_class, idw_power)) %>% 
  rowwise() %>%
  mutate(
    plot_label = paste0(
      "rho == ",
      sprintf("%.2f", obs_rho),
      " obs p = ",
      sprintf("%.2f", rho_obs_pval),
      " perm p = ",
      sprintf("%.2f", rho_perm_p)
    ),
    plot_label_parse = paste0(
      'rho == "', sprintf("%.2f", obs_rho), 
      '" * "," ~ italic(p) == "', sprintf("%.2f", rho_perm_p), '"'
    ),
    plot1_label = paste0(
      'rho == "', sprintf("%.2f", obs_rho), '"'
    ),
    plot2_label = paste0(
      'italic(p) == "', sprintf("%.2f", rho_perm_p), '"'
    ),
    plot3_label = paste0(
      'rho == "', sprintf("%.2f", obs_rho), 
      '" * "," ~ italic(p) == "', sprintf("%.2f", rho_perm_p), '"'
    )
  ) %>%
  mutate(
    x = 0.5,
    y = ifelse(arm == "azithro", 130, 142),
    dens_y = ifelse(arm == "azithro", 4.3, 4.75)
  ) %>%
  ungroup() %>%
  mutate(arm_f = factor(arm, levels = c("placebo", "azithro"), ordered = TRUE))

mls_dat <- amr_dat_raw %>%
  dplyr::filter(ab_class == "MLS")

fig2_dat <- morb_tx_int_raw %>%
  dplyr::filter(idw_power == 1) %>%
  dplyr::select(grappe, arm, tx_type, tx_int) %>%
  left_join(
    mls_dat %>% dplyr::select(grappe, phase, avg_res),
    by = "grappe"
  ) %>%
  mutate(arm_f = factor(arm, levels = c("placebo", "azithro"), ordered = TRUE))

```

```{r panel a}
baseline_pri <- ggplot(aes = aes()) +
  geom_point(data = subset(fig2_dat, phase == "Baseline" & tx_type == "azithro"), 
             aes(y = avg_res, x = tx_int, group = arm, color = arm),
             size = 3.5,
             alpha = 0.6) +
  geom_text(data = subset(cor_tx_int, phase == "Baseline" & tx_type == "azithro"),
    aes(label = plot3_label, y = y, group = arm, color = arm),
    x = 0,
    parse = TRUE,
    show.legend = FALSE,
    size = 5,
    hjust = 0
  ) +
  ggtitle("Baseline") +
  theme_minimal(base_size = 14) +
  theme(legend.position = "bottom",
        plot.title = element_text(size = 16, hjust = 0.5)) +
  scale_y_continuous(limits = c(0, 150), name = "MLS resistance gene abundance\n(normalized reads/million)") +
  scale_x_continuous(limits = c(0, 1),
                     name = "Geographic treatment intensity of azithromycin",
                     n.breaks = 6) +
  scale_color_manual(
    name = "Monitoring village treatment",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  ) +
  guides(color = guide_legend(override.aes = list(
    shape = 15,
    alpha = 0.8,
    size = 5
  )))

baseline_pri

ggsave(baseline_pri, filename = here("figs", "manuscript", "fig2-panelA.png"), 
       width = 6, height = 4.5, dpi = 600, bg = "white")
```

```{r panel c}
baseline_nce <- ggplot(aes = aes()) +
  geom_point(data = subset(fig2_dat, phase == "Baseline" & tx_type == "placebo"), 
             aes(y = avg_res, x = tx_int, group = arm, color = arm),
             size = 3.5,
             alpha = 0.6) +
  geom_text(data = subset(cor_tx_int, phase == "Baseline" & tx_type == "placebo"),
    aes(label = plot3_label, y = y, group = arm, color = arm),
    x = 0,
    parse = TRUE,
    show.legend = FALSE,
    size = 5,
    hjust = 0
  ) +
  ggtitle("Baseline") +
  theme_minimal(base_size = 14) +
  theme(legend.position = "bottom",
        plot.title = element_text(size = 16, hjust = 0.5)) +
  scale_y_continuous(limits = c(0, 150), name = "MLS resistance gene abundance\n(normalized reads/million)") +
  scale_x_continuous(limits = c(0, 1),
                     name = "Geographic treatment intensity of placebo",
                     n.breaks = 6) +
  scale_color_manual(
    name = "Monitoring village treatment",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  ) +
  guides(color = guide_legend(override.aes = list(
    shape = 15,
    alpha = 0.8,
    size = 5
  )))

baseline_nce

ggsave(baseline_nce, filename = here("figs", "manuscript", "fig2-panelC.png"), 
       width = 6, height = 4.5, dpi = 600, bg = "white")
```

```{r panel b}
pri_24 <- ggplot(aes = aes()) +
  geom_point(data = subset(fig2_dat, phase == "24 months" & tx_type == "azithro"), 
             aes(y = avg_res, x = tx_int, group = arm, color = arm),
             size = 3.5,
             alpha = 0.6) +
  geom_text(data = subset(cor_tx_int, phase == "24 months" & tx_type == "azithro"),
    aes(label = plot3_label, y = 142, group = arm, color = arm),
    x = 0,
    parse = TRUE,
    show.legend = FALSE,
    size = 5,
    hjust = 0
  ) +
  facet_wrap(~ arm_f, nrow = 1, labeller = labeller(rows = ""), scales = "free") +
  ggtitle("24 months") +
  theme_minimal(base_size = 14) +
  theme(strip.text = element_blank(), 
        legend.position = "bottom",
        plot.title = element_text(size = 16, hjust = 0.5)) +
  scale_y_continuous(limits = c(0, 150), name = "MLS resistance gene abundance\n(normalized reads/million)") +
  scale_x_continuous(limits = c(0, 1),
                     name = "Geographic treatment intensity of azithromycin",
                     n.breaks = 6) +
  scale_color_manual(
    name = "Monitoring village treatment",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  ) +
  guides(color = guide_legend(override.aes = list(
    shape = 15,
    alpha = 0.8,
    size = 5
  )))

pri_24

ggsave(pri_24, filename = here("figs", "manuscript", "fig2-panelB.png"), 
       width = 6, height = 4.5, dpi = 600, bg = "white")
```

```{r panel d}
nce_24 <- ggplot(aes = aes()) +
  geom_point(data = subset(fig2_dat, phase == "24 months" & tx_type == "placebo"), 
             aes(y = avg_res, x = tx_int, group = arm, color = arm),
             size = 3.5,
             alpha = 0.6) +
  geom_text(data = subset(cor_tx_int, phase == "24 months" & tx_type == "placebo"),
    aes(label = plot3_label, y = 142, group = arm, color = arm),
    x = 0,
    parse = TRUE,
    show.legend = FALSE,
    size = 5,
    hjust = 0
  ) +
  facet_wrap(~ arm_f, nrow = 1, labeller = labeller(rows = ""), scales = "free") +
  ggtitle("24 months") +
  theme_minimal(base_size = 14) +
  theme(strip.text = element_blank(), 
        legend.position = "bottom",
        plot.title = element_text(size = 16, hjust = 0.5)) +
  scale_y_continuous(limits = c(0, 150), name = "MLS resistance gene abundance\n(normalized reads/million)") +
  scale_x_continuous(limits = c(0, 1),
                     name = "Geographic treatment intensity of placebo",
                     n.breaks = 6) +
  scale_color_manual(
    name = "Monitoring village treatment",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  ) +
  guides(color = guide_legend(override.aes = list(
    shape = 15,
    alpha = 0.8,
    size = 5
  )))

nce_24

ggsave(nce_24, filename = here("figs", "manuscript", "fig2-panelD.png"), 
       width = 6, height = 4.5, dpi = 600, bg = "white")
```

```{r fig 2}

design = "
AB
CD
"

fig2_plot <- list(baseline_pri, pri_24, baseline_nce, nce_24) |>
  wrap_plots(nrow = 2, ncol = 2) + 
  plot_annotation(tag_levels = 'A') + 
  plot_layout(guides = 'collect', widths = c(0.32, 0.68), heights = c(1, 1), design = design) & 
  theme(legend.position = 'bottom')

fig2_plot

ggsave(fig2_plot, filename = here("figs", "manuscript", "fig2.png"), 
       width = 12, height = 9, dpi = 600, bg = "white")

```

