---
title: "Supplementary figures for between-cluster geographical spillover of AMR in MORDOR at 24 months"
# author: "Ariktha Srivathsan"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    code_folding: hide
---

```{=html}
<style type="text/css">

body{ /* Normal  */
      font-size: 12px;
  }
td {  /* Table  */
  font-size: 15px;
}
h1.title {
  font-size: 26px;
  color: Black;
}
h1 { /* Header 1 */
  font-size: 24px;
  color: Black;
}
h2 { /* Header 2 */
    font-size: 20px;
  color: Black;
}
h3 { /* Header 3 */
  color: Black;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>
```

```{r setup}

knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE,
                      fig.width = 6, fig.height = 8, dpi = 300) 

rm(list = ls())       

library(here)
library(patchwork)
```

```{r load data}
source(here("R", "00-config.R"))

cor_tx_int_raw <- readRDS(here("data", "final", "cor_tx_int.RDS"))
morb_tx_int_raw <- readRDS(here("data", "final", "morb_tx_int.RDS"))
amr_dat_raw <- readRDS(here("data", "final", "amr_dat.RDS"))
morb_rings_raw <- readRDS(here("data", "final", "morb_rings.RDS"))

morb_pop_raw <- readRDS(here("data", "final", "hrsl_rings.RDS"))
morb_csi_raw <- readRDS(here("data", "final", "morb_csi.RDS"))
```

# Supp fig 1: Power = 2

```{r supp fig 1 prep}

cor_tx_int_pwr2 <- cor_tx_int_raw %>%
  dplyr::filter(idw_power == 2) %>%
  dplyr::filter(ab_class == "MLS") %>%
  dplyr::filter(tx_type == "azithro") %>%
  dplyr::select(- c(ab_class, idw_power)) %>% 
  rowwise() %>%
  mutate(
    plot_label = paste0(
      "rho == ",
      sprintf("%.2f", obs_rho),
      " obs p = ",
      sprintf("%.2f", rho_obs_pval),
      " perm p = ",
      sprintf("%.2f", rho_perm_p)
    ),
    plot_label_parse = paste0(
      'rho == "', sprintf("%.2f", obs_rho), 
      '" * "," ~ italic(p) == "', sprintf("%.2f", rho_perm_p), '"'
    )
  ) %>%
  mutate(
    x = 0.5,
    y = ifelse(arm == "azithro", 130, 142),
    dens_y = ifelse(arm == "azithro", 4.3, 4.75)
  ) %>%
  ungroup() %>%
  mutate(arm_f = factor(arm, levels = c("placebo", "azithro"), ordered = TRUE))

mls_dat <- amr_dat_raw %>%
  dplyr::filter(ab_class == "MLS")

pwr2_dat <- morb_tx_int_raw %>%
  dplyr::filter(idw_power == 2) %>%
  dplyr::filter(tx_type == "azithro") %>%
  dplyr::select(grappe, arm, tx_type, tx_int) %>%
  left_join(
    mls_dat %>% dplyr::select(grappe, phase, avg_res),
    by = "grappe"
  ) %>%
  mutate(arm_f = factor(arm, levels = c("placebo", "azithro"), ordered = TRUE))

```

```{r r supp fig 1, fig.width = 8}

ggplot(data = cor_tx_int_pwr2, aes(group = arm, color = arm)) +
  geom_point(
    data = pwr2_dat,
    aes(y = avg_res, x = tx_int),
    size = 3.5,
    alpha = 0.6
  ) +
  geom_text(
    aes(label = plot_label_parse, y = y),
    x = 1,
    parse = TRUE,
    show.legend = FALSE,
    size = 5,
    hjust = 1
  ) +
  theme_minimal(base_size = 16) + facet_wrap( ~ phase) +
  xlab("Azithromycin treatment intensity (IDW power = 2)") + ylab("Normalized Abundance of MLS\nResistance Determinants (reads/million)") +
  theme(legend.position = "none",
        panel.spacing.x = unit(1, "cm")) + ylim(c(0, 150)) + xlim(c(0, 1)) +
  scale_color_manual(
    name = "Arm",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  )

ggsave(
  here("figs", "manuscript", "supp-figs", "supp_fig1.png"),
  bg = "white",
  width = 8,
  height = 5
)

```

# Supp fig 2: Leave-one-out correlations

```{r supp fig 2 prep}

## Leave-one-out analysis functions

leave_one_out_corr <- function(x, y) {
  n <- length(x)
  corr <- numeric(n)
  for (i in 1:n) {
    x_loo <- x[-i]
    y_loo <- y[-i]
    corr[i] <- cor(x_loo, y_loo, method = "spearman")
  }
  
  return(corr)
}

## Reformat leave one out data

loo_cor <- morb_tx_int_raw %>%
  dplyr::filter(idw_power == 1) %>%
  # dplyr::filter(tx_type == "azithro") %>%
  dplyr::select(grappe, arm, tx_type, tx_int) %>%
  left_join(
    mls_dat %>% dplyr::select(grappe, phase, avg_res),
    by = "grappe"
  ) %>%
  group_by(arm, phase, tx_type) %>%
  mutate(loo_cor = leave_one_out_corr(avg_res, tx_int)) %>%
  ungroup() %>%
  mutate(experiment = factor(ifelse(tx_type == "azithro", 
                                    "Primary exposure", "Negative control exposure"), 
                             levels = c("Primary exposure", "Negative control exposure"), 
                             ordered = TRUE))

mls_cor <- cor_tx_int_raw %>%
  dplyr::filter(ab_class == "MLS",
                idw_power == 1) %>%
  mutate(experiment = factor(ifelse(tx_type == "azithro", 
                                    "Primary exposure", "Negative control exposure"), 
                             levels = c("Primary exposure", "Negative control exposure"), 
                             ordered = TRUE))

```

```{r supp fig 2, fig.width = 8}

ggplot() + geom_boxplot(data = loo_cor,
                        aes(
                          y = loo_cor,
                          x = arm,
                          color = arm,
                          group = arm
                        ),
                        outliers = FALSE) +
  geom_rug(data = loo_cor, aes(y = loo_cor, color = arm)) +
  geom_hline(data = mls_cor,
             aes(
               yintercept = obs_rho,
               color = arm,
               group = arm
             ),
             linetype = "dashed") +
  theme_minimal(base_size = 14) + facet_grid(vars(experiment), vars(phase)) +
  geom_hline(yintercept = 0) + ylab("Spearman correlation") + ylim(c(-0.2, 0.6)) +
  guides(x = "none") + theme(legend.position = "bottom", axis.title.x = element_blank()) +
  scale_color_manual(
    name = "Arm",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  ) 

ggsave(
  here("figs", "manuscript", "supp-figs", "supp_fig2.png"),
  bg = "white",
  width = 7,
  height = 5
)

```

#  Supp fig 3: Correlation of azithromycin doses and treatment intensity

```{r supp fig 3 prep}

dat_fig3 <- morb_rings_raw %>%
  dplyr::select(grappe, arm, ring_range_text, azithro_doses, total_children, outer_radius) %>%
  left_join(
    morb_tx_int_raw %>% 
      dplyr::filter(tx_type == "azithro", idw_power == 1) %>% 
      dplyr::select(grappe, arm, tx_int),
    by = c("grappe", "arm")
  ) %>% st_drop_geometry() %>%
  dplyr::filter(outer_radius <= 30)

```

```{r supp fig 3, fig.width = 8, fig.height = 5}

azithro_doses_plot <- ggplot(data = dat_fig3, 
                             aes(x = total_children / 1000, y = azithro_doses /
                                                    1000)) + 
  geom_point() +
  facet_wrap( ~ ring_range_text, nrow = 1) +
  ggpubr::stat_cor() + 
  theme_minimal(base_size = 14) +
  scale_x_continuous(name = expression("Number of children in the distance band x" ~
                                         10^3)) +
  scale_y_continuous(name = expression("Azithromycin doses\ndistributed in the band x" ~
                                         10^3)) +
  theme(axis.title.y = element_text(hjust = 0.5, vjust = 0.5))

azithro_txint_plot <- ggplot(data = dat_fig3, aes(x = total_children / 1000, y = tx_int)) + 
  geom_point() +
  facet_wrap( ~ ring_range_text, nrow = 1) +
  ggpubr::stat_cor() + 
  theme_minimal(base_size = 14) +
  scale_x_continuous(name = expression("Number of children in the distance band x" ~
                                         10^3)) +
  scale_y_continuous(name = expression("Geographical treatment\nintensity of azithromycin"))

supp_fig3_plot <- azithro_doses_plot / azithro_txint_plot +
  plot_annotation(tag_levels = 'A') 

supp_fig3_plot

ggsave(here("figs", "manuscript", "supp-figs", "supp_fig3.png"), 
       width = 8, height = 7, dpi = 300, bg = "white")

```

# Supp fig 4: Population density

```{r supp fig 4 prep}

band_area <- function(outer_radius) {
  inner_radius <- outer_radius - 10
  outer_area <- pi * outer_radius^2
  inner_area <- pi * inner_radius^2
  return(outer_area - inner_area)
}

band_area_tib <- tibble(outer_radius = seq(10, 30, by = 10)) %>%
  mutate(area = band_area(outer_radius))

morb_pop <- morb_pop_raw %>%
  dplyr::select(grappe, outer_radius, total_u5_pop) %>%
  left_join(band_area_tib, by = "outer_radius") %>%
  mutate(u5_pop_dens = total_u5_pop / area) %>%
  left_join(morb_rings_raw %>%
              st_drop_geometry() %>%
              dplyr::select(grappe, arm, ring_range_text, outer_radius, azithro_doses),
            by = c("grappe", "outer_radius")) %>%
  left_join(amr_dat_raw %>%
              dplyr::filter(ab_class == "MLS") %>%
              dplyr::select(grappe, phase, avg_res),
            by = "grappe", relationship = "many-to-many")

```

```{r supp fig 4}

p1 <- ggplot(morb_pop,
             aes(
               x = u5_pop_dens,
               y = azithro_doses,
               color = arm,
               group = arm
             )) +
  geom_point() +
  theme_minimal(base_size = 12) +
  ggpubr::stat_cor(
    method = "spearman",
    cor.coef.name = "rho",
    show.legend = FALSE,
    label.x.npc = "right",
    label.y.npc = "top",
    hjust = 1
  ) +
  facet_wrap( ~ ring_range_text) +
  scale_y_continuous(
    labels = function(x)
      x / 1000,
    name = expression(atop("Azithromycin doses", "in the band x" ~ 10^3)),
    limits = c(0, 30000)
  ) +
  scale_x_continuous(name = expression("Under-5 population density (children/km"^2*")"), limits = c(0, 40)) +
  theme(
    legend.position = "bottom",
    panel.spacing.x = unit(0.6, "cm"),
    axis.title.y = element_text(hjust = 0.5)
  ) +
  scale_color_manual(
    name = "Monitoring village treatment",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  )

p2 <- ggplot(morb_pop, aes(
  x = u5_pop_dens,
  y = avg_res,
  color = arm,
  group = arm
)) +
  geom_point() +
  theme_minimal(base_size = 12) +
  labs(y = "MLS resistance gene abundance\n(normalized reads/million)") +
  scale_x_continuous(name = expression(atop("Under-5 population density (children/km"^2*")",
                         "Data from High Resolution Settlement Layer, Meta data for good")), 
                     limits = c(0, 40)) +
  ggpubr::stat_cor(
    method = "spearman",
    cor.coef.name = "rho",
    show.legend = FALSE,
    label.x.npc = "right",
    label.y.npc = "top",
    hjust = 1
  ) +
  facet_grid(phase ~ ring_range_text, switch = "y") +
  scale_color_manual(
    name = "Monitoring village treatment",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  ) +
  theme(legend.position = "bottom",
        panel.spacing.x = unit(0.6, "cm")) +
  ylim(c(0, 200))

hrsl_plot <- p1 / p2 +
  plot_annotation(tag_levels = 'A') + plot_layout(heights = c(0.4, 0.6), guides = "collect")  &
  theme(legend.position = 'bottom')

hrsl_plot

ggsave(here("figs", "manuscript", "supp-figs", "supp_fig4.png"), hrsl_plot, width = 8, height = 7, dpi = 600, bg = "white")


```

# Supp fig 5: Distance to CSI

```{r supp fig 5 prep}

morb_csi <- morb_csi_raw %>%
  st_drop_geometry() %>%
  dplyr::select(grappe, dist_csi) %>%
  left_join(
    morb_tx_int_raw %>% 
      dplyr::filter(tx_type == "azithro", idw_power == 1) %>% 
      dplyr::select(grappe, arm, tx_int),
    by = "grappe"
  ) %>%
  left_join(
    mls_dat %>% dplyr::select(grappe, phase, avg_res),
    by = "grappe"
  )

```

```{r supp fig 5}

q1 <- ggplot(morb_csi, aes(y = tx_int, x = dist_csi, color = arm)) + 
  geom_point() + theme_minimal(base_size = 14) +
  labs(y = "Geographic treatment\nintensity of azithromycin", 
       x = "Distance to nearest primary health post (km)") +
  ggpubr::stat_cor(
    show.legend = FALSE,
    label.x.npc = "right",
    label.y.npc = "top",
    hjust = 1
  ) +
  scale_color_manual(
    name = "Arm",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  )

q2 <- ggplot(morb_csi, aes(x = dist_csi, y = avg_res, color = arm)) + 
  geom_point() +
  theme_minimal(base_size = 14) + 
  xlab("Distance to nearest primary health post (km)") + 
  ylab("MLS resistance gene abundance\n(normalized reads/million)") +
  ggpubr::stat_cor(
    show.legend = FALSE,
    label.x.npc = "right",
    label.y.npc = "top",
    hjust = 1
  ) + facet_wrap( ~ phase) +
  scale_color_manual(
    name = "Arm",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  ) +
  theme(panel.spacing.x = unit(0.8, "cm"))

csi_plot <- q1 / q2 + plot_annotation(tag_levels = 'A') + plot_layout(guides = "collect") &
  theme(legend.position = 'bottom')

csi_plot

ggsave(here("figs", "manuscript", "supp-figs", "supp_fig5.png"), 
       csi_plot, width = 7, height = 7, dpi = 600, bg = "white")


```

# Supp fig 6: Other classes of antibiotics

```{r supp fig 6 prep}

other_abs_dat <- amr_dat_raw %>%
  dplyr::filter(ab_class != "MLS") %>%
  dplyr::select(grappe, phase, ab_class, avg_res) %>%
  left_join(
    morb_tx_int_raw %>% 
      dplyr::filter(tx_type == "azithro", idw_power == 1) %>% 
      dplyr::select(grappe, arm, tx_int),
    by = "grappe"
  )

other_abs_cor <- cor_tx_int_raw %>%
  dplyr::filter(ab_class != "MLS", idw_power == 1, tx_type == "azithro") %>%
  dplyr::select(arm, phase, ab_class, obs_rho, rho_perm_p) %>%
  mutate(plot_label_parse = paste0(
    'rho == "', sprintf("%.2f", obs_rho),
    '" * "," ~ italic(p) == "', sprintf("%.2f", rho_perm_p), '"'),
    rho_label_parse = paste0(
    'rho == "', sprintf("%.2f", obs_rho), '"')) %>%
  mutate(x = 1, y = ifelse(arm == "azithro", 1850, 1600))

other_abs_grp <- tibble(ab_class = unique(ab_classes_of_interest[which(ab_classes_of_interest != "MLS")]),
                        group_id = rep(c(1:3), each = 5)) %>%
  mutate(ab_class_text = case_when(
    ab_class == "Multi.drug.resistance" ~ "MDR",
    ab_class == "betalactams" ~ "Beta-lactams",
    TRUE ~ ab_class
  ))

other_abs_dat <- other_abs_dat %>% 
  left_join(other_abs_grp, by = "ab_class")
other_abs_cor <- other_abs_cor %>%
  left_join(other_abs_grp, by = "ab_class")
  
```

```{r supp fig 6 with p, fig.height = 10, fig.width = 10}

fig6_p1_with_p <- ggplot(data = subset(other_abs_dat, group_id == 1), 
                  aes(color = arm, group = arm)) +
  geom_point(aes(y = avg_res, x = tx_int)) +
  geom_text(
    data = subset(other_abs_cor, group_id == 1),
    aes(label = plot_label_parse, x = x, y = y),
    parse = TRUE,
    show.legend = FALSE,
    size = 4,
    hjust = 1
  ) +
  theme_minimal(base_size = 15) +
  facet_grid(vars(ab_class_text), vars(phase), switch = "y") +
  ylab("Normalized Abundance of Resistance Determinants (reads/million)") +
  theme(
    legend.position = "bottom",
    panel.spacing.x = unit(0.3, "cm"),
    axis.text.x = element_text(angle = 30, hjust = 1)
  ) +
  scale_color_manual(
    name = "Monitoring village treatment",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  )  +
  scale_x_continuous(n.breaks = 6, name = "Geographic treatment intensity of azithromycin") +
  ylim(c(0, 2000))


fig6_p2_with_p <- ggplot(data = subset(other_abs_dat, group_id == 2), 
                  aes(color = arm, group = arm)) +
  geom_point(aes(y = avg_res, x = tx_int)) +
  geom_text(
    data = subset(other_abs_cor, group_id == 2),
    aes(label = plot_label_parse, x = x, y = y),
    parse = TRUE,
    show.legend = FALSE,
    size = 4,
    hjust = 1
  ) +
  theme_minimal(base_size = 15) +
  facet_grid(vars(ab_class_text), vars(phase), switch = "y") +
  ylab("Normalized Abundance of Resistance Determinants (reads/million)") +
  theme(
    legend.position = "bottom",
    panel.spacing.x = unit(0.3, "cm"),
    axis.text.x = element_text(angle = 30, hjust = 1)
  ) +
  scale_color_manual(
    name = "Monitoring village treatment",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  )  +
  scale_x_continuous(n.breaks = 6, name = "Geographic treatment intensity of azithromycin") +
  ylim(c(0, 2000))

fig6_p3_with_p <- ggplot(data = subset(other_abs_dat, group_id == 3), 
                  aes(color = arm, group = arm)) +
  geom_point(aes(y = avg_res, x = tx_int)) +
  geom_text(
    data = subset(other_abs_cor, group_id == 3),
    aes(label = plot_label_parse, x = x, y = y),
    parse = TRUE,
    show.legend = FALSE,
    size = 4,
    hjust = 1
  ) +
  theme_minimal(base_size = 15) +
  facet_grid(vars(ab_class_text), vars(phase), switch = "y") +
  ylab("Normalized Abundance of Resistance Determinants (reads/million)") +
  theme(
    legend.position = "bottom",
    panel.spacing.x = unit(0.3, "cm"),
    axis.text.x = element_text(angle = 30, hjust = 1)
  ) +
  scale_color_manual(
    name = "Monitoring village treatment",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  )  +
  scale_x_continuous(n.breaks = 6, name = "Geographic treatment intensity of azithromycin") +
  ylim(c(0, 2000))

other_abs_plot_with_p <- fig6_p1_with_p + fig6_p2_with_p + fig6_p3_with_p +
  plot_layout(guides = "collect", axes = "collect") & theme(legend.position = "bottom")

other_abs_plot_with_p

ggsave(here("figs", "manuscript", "supp-figs", "supp_fig6-with-p.png"), other_abs_plot_with_p, bg = "white", width = 11, height = 9, dpi = 300)

```

```{r supp fig 6, fig.height = 10, fig.width = 10}

fig6_p1 <- ggplot(data = subset(other_abs_dat, group_id == 1), 
                  aes(color = arm, group = arm)) +
  geom_point(aes(y = avg_res, x = tx_int)) +
  geom_text(
    data = subset(other_abs_cor, group_id == 1),
    aes(label = rho_label_parse, x = x, y = y),
    parse = TRUE,
    show.legend = FALSE,
    size = 4,
    hjust = 1
  ) +
  theme_minimal(base_size = 15) +
  facet_grid(vars(ab_class_text), vars(phase), switch = "y") +
  ylab("Normalized Abundance of Resistance Determinants (reads/million)") +
  theme(
    legend.position = "bottom",
    panel.spacing.x = unit(0.3, "cm"),
    axis.text.x = element_text(angle = 30, hjust = 1)
  ) +
  scale_color_manual(
    name = "Monitoring village treatment",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  )  +
  scale_x_continuous(n.breaks = 6, name = "Geographic treatment intensity of azithromycin") +
  ylim(c(0, 2000))


fig6_p2 <- ggplot(data = subset(other_abs_dat, group_id == 2), 
                  aes(color = arm, group = arm)) +
  geom_point(aes(y = avg_res, x = tx_int)) +
  geom_text(
    data = subset(other_abs_cor, group_id == 2),
    aes(label = rho_label_parse, x = x, y = y),
    parse = TRUE,
    show.legend = FALSE,
    size = 4,
    hjust = 1
  ) +
  theme_minimal(base_size = 15) +
  facet_grid(vars(ab_class_text), vars(phase), switch = "y") +
  ylab("Normalized Abundance of Resistance Determinants (reads/million)") +
  theme(
    legend.position = "bottom",
    panel.spacing.x = unit(0.3, "cm"),
    axis.text.x = element_text(angle = 30, hjust = 1)
  ) +
  scale_color_manual(
    name = "Monitoring village treatment",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  )  +
  scale_x_continuous(n.breaks = 6, name = "Geographic treatment intensity of azithromycin") +
  ylim(c(0, 2000))

fig6_p3 <- ggplot(data = subset(other_abs_dat, group_id == 3), 
                  aes(color = arm, group = arm)) +
  geom_point(aes(y = avg_res, x = tx_int)) +
  geom_text(
    data = subset(other_abs_cor, group_id == 3),
    aes(label = rho_label_parse, x = x, y = y),
    parse = TRUE,
    show.legend = FALSE,
    size = 4,
    hjust = 1
  ) +
  theme_minimal(base_size = 15) +
  facet_grid(vars(ab_class_text), vars(phase), switch = "y") +
  ylab("Normalized Abundance of Resistance Determinants (reads/million)") +
  theme(
    legend.position = "bottom",
    panel.spacing.x = unit(0.3, "cm"),
    axis.text.x = element_text(angle = 30, hjust = 1)
  ) +
  scale_color_manual(
    name = "Monitoring village treatment",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  )  +
  scale_x_continuous(n.breaks = 6, name = "Geographic treatment intensity of azithromycin") +
  ylim(c(0, 2000))

other_abs_plot <- fig6_p1 + fig6_p2 + fig6_p3 +
  plot_layout(guides = "collect", axes = "collect") & theme(legend.position = "bottom")

other_abs_plot

ggsave(here("figs", "manuscript", "supp-figs", "supp_fig6.png"), other_abs_plot, bg = "white", width = 11, height = 9, dpi = 300)

```


# Supp fig 7: Village size

```{r supp fig 7 prep}

cor_supp_fig7 <- cor_tx_int_raw %>%
  dplyr::filter(idw_power == 1, tx_type == "azithro") %>%
  dplyr::filter(ab_class == "MLS") %>%
  dplyr::select(- c(ab_class, idw_power)) %>% 
  rowwise() %>%
  mutate(
    plot_label_parse = paste0(
      'rho == "', sprintf("%.2f", obs_rho), 
      '" * "," ~ italic(p) == "', sprintf("%.2f", rho_perm_p), '"'
    )
  ) %>%
  mutate(
    x = 0.5,
    y = ifelse(arm == "azithro", 130, 142),
    dens_y = ifelse(arm == "azithro", 4.3, 4.75)
  ) %>%
  ungroup() %>%
  mutate(arm_f = factor(arm, levels = c("placebo", "azithro"), ordered = TRUE))

dat_supp_fig7 <- morb_tx_int_raw %>%
  dplyr::filter(idw_power == 1, tx_type == "azithro") %>%
  dplyr::select(grappe, arm, tx_int, n_children) %>%
  left_join(
    mls_dat %>% dplyr::select(grappe, phase, avg_res),
    by = "grappe"
  )

```

```{r supp fig 7}

ggplot() +
  geom_point(data = dat_supp_fig7, 
             aes(y = avg_res, x = tx_int, group = arm, color = arm, size = n_children),
             alpha = 0.6) +
  geom_text(data = cor_supp_fig7,
    aes(label = plot_label_parse, y = y, group = arm, color = arm),
    x = 0,
    parse = TRUE,
    show.legend = FALSE,
    size = 5,
    hjust = 0
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "bottom", legend.box = "vertical") +
  scale_y_continuous(limits = c(0, 150), 
                     name = "MLS resistance gene abundance\n(normalized reads/million)") +
  scale_x_continuous(limits = c(0, 1),
                     name = "Geographic treatment intensity of azithromycin",
                     n.breaks = 6) +
  scale_color_manual(
    name = "Monitoring village treatment",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  ) +
  scale_size_continuous(
    name = "Number of children in the village", 
    breaks = c(250, 500, 1000)
  ) +
  facet_wrap(~ phase) +
  guides(color = guide_legend(override.aes = list(shape = 15, alpha = 0.8, size = 5)))

ggsave(here("figs", "manuscript", "supp-figs", "supp_fig7.png"), 
       width = 8, height = 5.3, bg = "white")

```

