---
title: "Manuscript figure 2 for between-cluster geographical spillover of AMR in MORDOR at 24 months"
# author: "Ariktha Srivathsan"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    code_folding: hide
---

<style type="text/css">

body{ /* Normal  */
      font-size: 12px;
  }
td {  /* Table  */
  font-size: 15px;
}
h1.title {
  font-size: 26px;
  color: Black;
}
h1 { /* Header 1 */
  font-size: 24px;
  color: Black;
}
h2 { /* Header 2 */
    font-size: 20px;
  color: Black;
}
h3 { /* Header 3 */
  color: Black;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>

```{r setup}

knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE,
                      fig.width = 6, fig.height = 8, dpi = 300) 

rm(list = ls())       

library(here)
library(ggspatial)
library(patchwork)
```

```{r load data}
source(here("R", "00-config.R"))

morb_rings_raw <- readRDS(here("data", "clean", "morb_rings.RDS"))

amr_dat_raw <- readRDS(here("data", "clean", "amr_dat.RDS"))

cor_rings <- readRDS(here("data", "output", "cor_ring.RDS"))

morb_gps <- readRDS(here("data", "clean", "morb_gps.RDS"))
main_gps <- readRDS(here("data", "clean", "main_gps.RDS"))

morb_grappe <- readRDS(here("data", "clean", "morb_grappe.RDS")) %>%
  left_join(morb_gps, by = "grappe") %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = global_crs, remove = FALSE)

main_grappe <- readRDS(here("data", "clean", "main_grappe.RDS")) %>%
  left_join(main_gps, by = "grappe") %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = global_crs, remove = FALSE)

niger_shp_raw <- st_read(
  here(
    "data",
    "untouched",
    "niger_shapefiles",
    "NER_admbnda_adm2_IGNN_20230720.shp"
  )
)

niger_shp <- niger_shp_raw %>%
  mutate(mordor_states = ifelse(ADM2_FR %in% c("Falmey", "Boboye", "Loga"), TRUE, FALSE)) %>%
  dplyr::filter(mordor_states == TRUE)
```

```{r data prep}

morb_grappe_names <- c("TEGOIZE KOIRA ZENO", "MOUNBEINA FANDOGA", "SETTI I", "TASSIEL")

morb_pt <- morb_grappe %>%
  dplyr::filter(grappe %in% morb_grappe_names)

morb_pt_utm <- st_transform(morb_pt$geometry, crs = 7801)

rings_perm <- cor_rings %>%
  dplyr::filter(ab_class == "MLS") %>%
  dplyr::select(- c(ab_class)) %>%
  group_by(arm, phase, ring_range_text) %>%
  mutate(
    plot_label = paste0(
      "rho = ",
      sprintf("%.2f", obs_rho),
      " obs p = ",
      sprintf("%.2f", rho_obs_pval),
      " perm p = ",
      sprintf("%.2f", rho_perm_p)
    ),
    plot_label_parse = paste0(
      'rho == "', sprintf("%.2f", obs_rho), 
      '" * "," ~ italic(p) == "', sprintf("%.2f", rho_perm_p), '"'
    ),
    x = 30000,
    y = ifelse(arm == "azithro", 148, 137)
  ) %>%
  ungroup() %>%
  mutate(outer_radius = as.numeric(sub(".*-\\s*(\\d+)\\s*km", "\\1", ring_range_text))) %>%
  dplyr::filter(outer_radius <= 30) %>%
  dplyr::filter(tx_type == "azithro")

morb_rings <- morb_rings_raw %>%
  dplyr::filter(outer_radius <= 30) %>%
  dplyr::select(grappe, arm, ring_range_text, outer_radius, 
                placebo_doses, azithro_doses, total_grappes) %>%
  st_drop_geometry() %>% 
  distinct() %>%
  mutate(arm = factor(arm, levels = c("azithro", "placebo"), ordered = TRUE))

mls_dat <- amr_dat_raw %>%
  dplyr::filter(ab_class == "MLS") %>%
  dplyr::select(grappe, phase, avg_res)

morb_rings <- morb_rings %>%
  left_join(mls_dat, by = c("grappe"))
```

```{r panel a}
rings_map <- ggplot() + 
  geom_sf(data = niger_shp_raw, fill = "#f9fafa") +
  geom_point(data = main_grappe,
             aes(x = longitude, y = latitude, color = factor(arm)),
             alpha = 0.2) +
  geom_point(
    data = subset(morb_grappe, grappe %in% morb_grappe_names),
    aes(x = longitude, y = latitude)
  ) +
  scale_color_manual(
    values = arms_colors,
    breaks = c("azithro", "placebo"),
    name = "Monitoring village treatment",
    labels = c("Azithromycin", "Placebo")
  ) +
  scale_x_continuous(
    breaks = c(2.4, 2.8, 3.2, 3.6),
    limits = c(2.45, 3.78),
    name = "Longitude"
  ) +
  scale_y_continuous(limits = c(12.28, 13.95), name = "Latitude") + 
  annotation_scale(aes(location = "br")) + theme_minimal(base_size = 14) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    plot.margin = unit(c(0, 0, 0, 0), "cm")
  ) +
  geom_sf(data = morb_pt, aes(geometry = geometry)) +
  geom_sf(
    data = st_buffer(morb_pt_utm, 10 * 1000),
    fill = NA,
    color = "red"
  ) +
  geom_sf(
    data = st_buffer(morb_pt_utm, 20 * 1000),
    fill = NA,
    color = "red"
  ) +
  geom_sf(
    data = st_buffer(morb_pt_utm, 30 * 1000),
    fill = NA,
    color = "red"
  ) +
  # guides(color = guide_legend(override.aes = list(alpha = 0.7))) +
  guides(color = "none")

rings_map

ggsave(rings_map, filename = here("figs", "manuscript", "fig3-panelA.png"), 
       width = 6, height = 4.5, dpi = 600, bg = "white")
```


```{r panel b, fig.width = 6, fig.height = 4}

rings_grappes_plot <- ggplot(subset(morb_rings, outer_radius <= 30)) +
  geom_boxplot(aes(
    y = arm,
    x = total_grappes,
    group = arm,
    colour = arm
  ),
  show.legend = FALSE) +
  geom_point(aes(
    y = arm,
    x = total_grappes,
    group = arm,
    colour = arm
  )) +
  facet_grid(vars(ring_range_text)) + theme_minimal(base_size = 14) + guides(color = "none") +
  scale_x_continuous(
    limits = c(0, 110),
    breaks = seq(0, 120, by = 20),
    name = "Number of villages in the band"
  ) +
  scale_y_discrete(
    limits = c("placebo", "azithro")
  ) +
  theme(
    axis.text.y = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "none"
  ) +
  scale_color_manual(
    name = "Monitoring village treatment",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  )

rings_grappes_plot

ggsave(rings_grappes_plot, filename = here("figs", "manuscript", "fig3-panelB.png"), 
       width = 6, height = 4.5, dpi = 600, bg = "white")
```


```{r panel c}

rings_corr_plot <- 
  ggplot(morb_rings, aes(color = arm, group = arm)) +
  geom_point(aes(x = azithro_doses, y = avg_res)) + 
  geom_rug(aes(y = avg_res), sides = "r", show.legend = FALSE) +
  geom_text(
    data = subset(rings_perm, outer_radius <= 30),
    aes(label = plot_label_parse, x = x, y = y),
    parse = TRUE,
    show.legend = FALSE,
    size = 4,
    hjust = 1
  ) +  
  theme_minimal(base_size = 14) +
  scale_color_manual(
    name = "Monitoring village treatment",
    breaks = c("azithro", "placebo"),
    labels = c("Azithromycin", "Placebo"),
    values = arms_colors
  ) +
  facet_grid(vars(ring_range_text), vars(phase)) +
  scale_x_continuous(
    labels = function(x)
      x / 1000,
    limits = c(0, 30000),
    name = expression("Azithromycin doses in the band x" ~ 10^3)
  ) +
  scale_y_continuous(limits = c(0, 149), name = "MLS resistance gene abundance (normalized reads/million)") +
  theme(legend.position = "bottom",
        panel.spacing.x = unit(1, "cm"))

rings_corr_plot

ggsave(rings_corr_plot, filename = here("figs", "manuscript", "fig3-panelC.png"), 
       width = 6, height = 4.5, dpi = 600, bg = "white")
```

```{r fig 3, fig.width = 10, fig.height = 8}

(rings_map/rings_grappes_plot) | rings_corr_plot

design <- "
13
23
44
"

fig3_plot <- rings_map + rings_grappes_plot + rings_corr_plot + guide_area() +
  plot_layout(design = design, guides = "collect", heights = c(0.8, 0.5, 0.1), widths = c(0.6, 1)) + 
  plot_annotation(tag_levels = 'A') 

fig3_plot

ggsave(fig3_plot, filename = here("figs", "manuscript", "fig3.png"), width = 9, height = 9)

```

